"""Added review model

Revision ID: 303c1b972468
Revises: cf63d2a9b986
Create Date: 2023-09-01 16:01:02.646861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303c1b972468'
down_revision = 'cf63d2a9b986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('restuarant_id', sa.Integer(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['restuarant_id'], ['restuarants.restuarant_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
