"""Added Restuarant Model

Revision ID: d9a523677c81
Revises: 4339026ce2f5
Create Date: 2023-09-01 13:59:23.055462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a523677c81'
down_revision = '4339026ce2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restuarants',
    sa.Column('restuarant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('restuarant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restuarants')
    # ### end Alembic commands ###
